AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  SmiirlCounterFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: handler.handler
      Runtime: nodejs20.x
      CodeUri: .
      Environment:
        Variables:
          COMPANY_ID: !Ref CompanyId
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowMethods: '*'
          AllowOrigins: '*'

Parameters:
  CompanyId:
    Type: String
    Description: Company ID